version: '3.8'
services:
  meilisearch:
    image: getmeili/meilisearch:v1.7
    container_name: meilisearch-1
    ports:
      - "7700:7700"
    volumes:
      - "./meili_data:/meili_data"
    environment:
      MEILI_ENV: development
    restart: unless-stopped